
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- WEB (del Código 2) ---
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiY3srMuLifiIF38W1jUJmLVZd-Y1axw4',
    appId: '1:227683941568:web:143cd899a7c34549d20125',
    messagingSenderId: '227683941568',
    projectId: 'twitterclone-5dd8f',
    authDomain: 'twitterclone-5dd8f.firebaseapp.com',
    storageBucket: 'twitterclone-5dd8f.firebasestorage.app',
  );

  // --- ANDROID (usa el de Código 2, NO el de Código 1 para evitar conflictos) ---
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYHlQ4w33Xsf3SuAeGc_3NfdqAwG0M4rA',
    appId: '1:227683941568:android:2ac6c66082cc4be7d20125',
    messagingSenderId: '227683941568',
    projectId: 'twitterclone-5dd8f',
    storageBucket: 'twitterclone-5dd8f.firebasestorage.app',
  );

  // --- IOS ---
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7FKiHcFGaW_sGkHAx00X7eurJbt1YbEk',
    appId: '1:227683941568:ios:6daf38d653c0e7acd20125',
    messagingSenderId: '227683941568',
    projectId: 'twitterclone-5dd8f',
    storageBucket: 'twitterclone-5dd8f.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  // --- MACOS ---
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7FKiHcFGaW_sGkHAx00X7eurJbt1YbEk',
    appId: '1:227683941568:ios:6daf38d653c0e7acd20125',
    messagingSenderId: '227683941568',
    projectId: 'twitterclone-5dd8f',
    storageBucket: 'twitterclone-5dd8f.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  // --- WINDOWS ---
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiY3srMuLifiIF38W1jUJmLVZd-Y1axw4',
    appId: '1:227683941568:web:64723fab9ec0baced20125',
    messagingSenderId: '227683941568',
    projectId: 'twitterclone-5dd8f',
    authDomain: 'twitterclone-5dd8f.firebaseapp.com',
    storageBucket: 'twitterclone-5dd8f.firebasestorage.app',
  );
}






