
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZgu1E_xrpOIaaSPExLzehHb9PwL1nNhA',
    appId: '1:485188841768:web:1e59236f348f4fe74fa01d',
    messagingSenderId: '485188841768',
    projectId: 'authfluttertwitterclone',
    authDomain: 'authfluttertwitterclone.firebaseapp.com',
    storageBucket: 'authfluttertwitterclone.firebasestorage.app',
  );

  // --- WEB (del Código 2) ---

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfOa4bNCKYFl8o0UQzUeYWhcHz2Lnyktc',
    appId: '1:485188841768:android:32ec74912464199d4fa01d',
    messagingSenderId: '485188841768',
    projectId: 'authfluttertwitterclone',
    storageBucket: 'authfluttertwitterclone.firebasestorage.app',
  );

  // --- ANDROID (usa el de Código 2, NO el de Código 1 para evitar conflictos) ---

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4qs3elTDC9ftmzfkcvA5AZB1KkPXo8PE',
    appId: '1:485188841768:ios:da4780eb2e232c9f4fa01d',
    messagingSenderId: '485188841768',
    projectId: 'authfluttertwitterclone',
    storageBucket: 'authfluttertwitterclone.firebasestorage.app',
    iosClientId: '485188841768-sdckn2j46ia2po740ua55bjh28nint63.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  // --- IOS ---

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4qs3elTDC9ftmzfkcvA5AZB1KkPXo8PE',
    appId: '1:485188841768:ios:da4780eb2e232c9f4fa01d',
    messagingSenderId: '485188841768',
    projectId: 'authfluttertwitterclone',
    storageBucket: 'authfluttertwitterclone.firebasestorage.app',
    iosClientId: '485188841768-sdckn2j46ia2po740ua55bjh28nint63.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  // --- MACOS ---

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZgu1E_xrpOIaaSPExLzehHb9PwL1nNhA',
    appId: '1:485188841768:web:99eba506d038005f4fa01d',
    messagingSenderId: '485188841768',
    projectId: 'authfluttertwitterclone',
    authDomain: 'authfluttertwitterclone.firebaseapp.com',
    storageBucket: 'authfluttertwitterclone.firebasestorage.app',
  );

  // --- WINDOWS ---
}
